{
 "title": "Web API Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Outbound Request Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats_counts.web-api.outbound.*.request-count, 3)"
    }
   ]
  },
  {
   "title": "Outbound Service Timing",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.timers.web-api.outbound.*.request-time.upper_90, 4)"
    }
   ]
  },
  {
   "title": "Incoming Status Codes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats_counts.web-api.inbound.response_code.*, 4)"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.timers.web-api.eventlag.upper_90)"
    }
   ]
  },
  {
   "title": "Server Memory Used / Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.web-api.server.memory.*, 5)"
    }
   ]
  },
  {
   "title": "V8 Heap Size / Limit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.web-api.server.heap.*, 5)"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.web-api.server.descriptors, 4)"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.web-api.server.conn, 4)"
    }
   ]
  }
 ]
}